config/routes.rb
Rails.application.routes.draw do
  # 顧客用

devise_for :users, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
 scope module: :public do

 root to: "homes#top"
 get 'search' => 'homes#search', as: 'search'
 get 'top', to: 'homes#top'
 get 'users/mypage' => 'users#mypage', as: 'mypage'
 get 'users/information/edit' => 'users#edit', as: 'edit_information'
 patch 'users/information' => 'users#update', as: 'update_information'
 get 'users/unsubscribe' => 'users#unsubscribe', as: 'confirm_unsubscribe'
 put 'users/information' => 'users#update'
 patch 'users/withdraw' => 'users#withdraw', as: 'withdraw_user'
#  get 'shops/:id/menu' => 'shops#menu', as: 'shop_menu'
 #get 'shops/:id/reviews' => 'reviews#index', as: 'shop_reviews'
 #get 'shops/:id/reviews/new' => 'shops#new_review', as: 'new_review'
 #resources :reviews, only: [:index,:show,:create,:new,:edit,:update,:destroy]
 resources :users, only: [:index,:show,:edit,:update] do
     resources :reviews
     #get 'myreview' => 'users#myreview'
 end
 resources :shops, only: [:index,:new,:create,:show,:edit,:update] do

   resources :reviews
   resources :menus, only: [:index,:new,:create,:destroy]

 end
 
 resources :reviews do
     resources :review_comments, only: [:index, :create, :destroy]
 end

 resources :genres, only: [:index]

 end


# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
namespace :admin do

get 'top' => 'homes#top', as: 'top'
get "about", to: "homes#about"
get 'search' => 'homes#search', as: 'search'
resources :shops do
  resources :reviews, only: [:index,:show,:destroy]
  resources :menus, only: [:index,:new,:create,:edit,:update,:destroy]
end

 resources :reviews, only: [:index,:show,:destroy] do
      resources :review_comments, only: [:index,:show,:destroy]
 end

resources :genres,only: [:index,:create,:edit,:update]

resources :users, only: [:index, :show, :edit, :update] 
  

end
end

app/models/shop.rb
class Shop < ApplicationRecord
  
  has_many :reviews
  has_many :menus
  
  validates :shop_name, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
  validates :opening_time, presence: true
  validates :holiday, presence: true
  
   
  
 
end

app/controllers/admin/shops_controller.rb
class Admin::ShopsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @shop = Shop.new
  end

  def index
    @shops = Shop.all.page(params[:page])
    @all_shops_count = @shops.count
  end

  def create
    @shop = Shop.new(shop_params)
    @shop.save ? (redirect_to admin_shop_path(@shop)) : (render :new)
  end

   def show
     @shop = Shop.find(params[:id])
   end

  def edit
     @shop = Shop.find(params[:id])
  end

  def update
    @shop = Shop.find(params[:id])
    @shop.update(shop_params) ? (redirect_to admin_shop_path(@shop)) : (render :edit)
  end
  
  def destroy
    @shop = Shop.find(params[:id])
    
    if @shop.destroy
    redirect_to admin_shops_path
    end
  end

  private

  def shop_params
    params.require(:shop).permit(:shop_name, :address, :telephone_number, :opening_time, :holiday, )
  end


end

app/helpers/admin/shops_helper.rb
module Admin::ShopsHelper
end

app/views/admin/shops/_form.html.erb
<%= form_with model:shop, url: url do |f| %>
	<%= render 'layouts/error_messages', resource: @shop %>

	<div class="flex">
		<div class="container">
			<div class="row no-gutters">
				<div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
					<h5 class="text-dark bg-light p-4 mb-0">店舗新規登録</h5>
						<div class="form-body p-4">
<form>
	
	<div><%= f.label :shop_name, "店舗名" %></div>
	<div><%= f.text_field :shop_name %></div>
				
	<div><%= f.label :address, "住所" %></div>
	<div><%= f.text_field :address %></div>
								
	<div><%= f.label :telephone_number, "電話番号" %></div>
	<div><%= f.text_field :telephone_number, placeholder: "09012345678" %> </div>
				
				
	<div><%= f.label :opening_time, "営業時間" %></div>
	<div><%= f.text_field :opening_time, placeholder: "11:00~15:00,17:00~21:00" %></div>
				
				
				
	<div><%= f.label :holiday, "定休日" %></div>
	<div><%= f.text_field :holiday %></div>
		
	
	<div class="flex align-center pl5">
			<%= f.submit submit, class: "btn btn-primary mt-3" %>
	</div>
	
	
<% end %>
</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	

app/views/admin/shops/_index.html.erb
<table class="table">
	<thead>
		<tr>
			
			<th>店舗名</th>
			<th>住所</th>
			<th>営業時間</th>
			<th>定休日</th>
			
		</tr>
	</thead>
	<tbody>
		<% shops.each do |shop| %>
			<tr>
				<td><%= link_to shop.shop_name,admin_shop_path(shop.id) %></td>
				<td><%= shop.address %></td>
				<td><%= shop.opening_time %></td>
				<td><%= shop.holiday %></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/admin/shops/edit.html.erb
<section class="inner">
	
  <%= render 'form', shop: @shop, url: admin_shop_path(@shop),target: :patch , submit: '更新' %>
</section>

app/views/admin/shops/index.html.erb
<section class="wrapper flex">
	<div class="inner">
		<% if params[:genre_id] %>
			<h2 class="section-ttl"><%= @genre.name %>の店舗一覧 (全<%= @all_shops_count %>件)</h2>
		<% else %>
			<h2 class="section-ttl">店舗一覧 (全<%= @all_shops_count %>件)</h2>
		<% end %>
	
		<% if @shops.first %> 
			<%= render 'index', shops: @shops %>
			<%= paginate @shops %>
		<% else %>
			<h3>対応する店舗はありませんでした。</h3>
		<% end %>
	</div>
</section>

app/views/admin/shops/new.html.erb
<section class="inner">
	
  <%= render 'form', shop: @shop, url: admin_shops_path, submit: '登録' %>
</section>

app/views/admin/shops/show.html.erb
<section class="inner">
	<h2 class="section-ttl">店舗詳細</h2>
	<div class="flex">
		<div>

		</div>
		<table class="table">
			<thead>
				
			</thead>
			<tbody>
				<tr>
					<td>店舗名</td>
					<td><%= @shop.shop_name %></td>
				</tr>
				<tr>
					<td>住所</td>
					<td><%= @shop.address %></td>
				</tr>

				<tr>
					<td>電話番号</td>
					<td><%= @shop.telephone_number %></td>
				</tr>

				<tr>
					<td>営業時間</td>
					<td><%= @shop.opening_time %></td>
				</tr>

				<tr>
					<td>定休日</td>
					<td><%= @shop.holiday %></td>
				</tr>

			</tbody>
		</table>
		<div class="flex align-center pl5">
			<%= link_to "編集", edit_admin_shop_path(@shop), class: "btn btn-success" %>
		</div>
		
		<div>
			<%= link_to "削除", admin_shop_path(@shop), method: :delete, data: {confirm: "本当に消しますか？"}, class:"btn btn-danger" %>
		</div>

		<div class ="flex align-center pl5">
			<%= link_to "レビュー一覧", admin_shop_reviews_path(@shop.id) %>
		</div>

		</div>
		 	<%= link_to "メニュー一覧", admin_shop_menus_path(@shop.id) %>
		<div>
	</div>