config/routes.rb
Rails.application.routes.draw do
  # 顧客用

devise_for :users, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
 scope module: :public do

 root to: "homes#top"
 get 'search' => 'homes#search', as: 'search'
 get 'top', to: 'homes#top'
 get 'users/mypage' => 'users#mypage', as: 'mypage'
 get 'users/information/edit' => 'users#edit', as: 'edit_information'
 patch 'users/information' => 'users#update', as: 'update_information'
 get 'users/unsubscribe' => 'users#unsubscribe', as: 'confirm_unsubscribe'
 put 'users/information' => 'users#update'
 patch 'users/withdraw' => 'users#withdraw', as: 'withdraw_user'
#  get 'shops/:id/menu' => 'shops#menu', as: 'shop_menu'
 #get 'shops/:id/reviews' => 'reviews#index', as: 'shop_reviews'
 #get 'shops/:id/reviews/new' => 'shops#new_review', as: 'new_review'
 #resources :reviews, only: [:index,:show,:create,:new,:edit,:update,:destroy]
 resources :users, only: [:index,:show,:edit,:update] do
     resources :reviews
     #get 'myreview' => 'users#myreview'
 end
 resources :shops, only: [:index,:new,:create,:show,:edit,:update] do

   resources :reviews
   resources :menus, only: [:index,:new,:create,:destroy]

 end
 
 resources :reviews do
     resources :review_comments, only: [:index, :create, :destroy]
 end

 resources :genres, only: [:index]

 end


# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
namespace :admin do

get 'top' => 'homes#top', as: 'top'
get "about", to: "homes#about"
get 'search' => 'homes#search', as: 'search'
resources :shops do
  resources :reviews, only: [:index,:show,:destroy]
  resources :menus, only: [:index,:new,:create,:edit,:update,:destroy]
end

 resources :reviews, only: [:index,:show,:destroy] do
      resources :review_comments, only: [:index,:show,:destroy]
 end

resources :genres,only: [:index,:create,:edit,:update]

resources :users, only: [:index, :show, :edit, :update] 
  

end
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @reviews = Shop.find(params[:shop_id]).reviews.page(params[:page])
    @all_reviews_count = @reviews.count
    
  end
  
  
  def show
     @review = Review.find(params[:id])
    
  end
  
  
  def destroy
    @review = Review.find(params[:id])
    @shop = @review.shop
    
    if @review.destroy
      redirect_to admin_shop_reviews_path(@shop)
    end
    
    
  end
  
   private

  def review_params
    params.require(:review).permit(:shop_id, :user_id, :review_comment_id, :title, :eated_menu, :comment,  :star)
  end
  
  
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/views/admin/reviews/index.html.erb
<section class="wrapper flex">
	<div class="inner">
	
			<h2 class="section-ttl">レビュー一覧 (全<%= @all_reviews_count %>件)</h2>
		
	<table class="table">
	<thead>
	
	</thead>
	<tbody>
		<% @reviews.each do |review| %>
			<tr>
				<td><%= link_to review.title,admin_shop_review_path(shop_id: review.shop_id, id: review.id) %></td>
			</tr>
		<% end %>
	</tbody>
</table>
		
		
	</div>
</section>

app/views/admin/reviews/show.html.erb
	<div>
		<div class="d-flex">

			<h3><%= @review.title %></h3>
		</div>
		<div class="d-flex">
			<p class="mr-1">食べたメニュー</p>
			<p><%= @review.eated_menu %></p>
		</div>
		<div class="d-flex">
			<p class="mr-1">コメント</p>
			<p><%= @review.comment %></p>
		</div>

	<!--ここからraty-->
	<div class="" id="star">

  <script>
		var elem = document.getElementById("star");
		var opt = {
		    size     : 36,
		    starOff:  '<%= asset_path('star-off.png') %>',
		    starOn : '<%= asset_path('star-on.png') %>',
		    scoreName: 'review[star]',
		    score: <%= @review.star %>,
		    half: false,
		    readOnly: true,
		}

		raty(elem, opt);
  </script>
  </div>
   <!--ここまで-->

		<div class="d-flex">
			<p class="mr-1">投稿者</p>
			<p><%= link_to @review.user.nickname,admin_user_path %></p>
		</div>
		<div class="d-flex">
			<p class="mr-1">ショップ</p>
			<p><%= link_to @review.shop.shop_name,admin_shop_path %></p>
		</div>




	<div>
  <p>コメント件数：<%= @review.review_comments.count %></p>
  <%= link_to "コメント一覧へ",admin_review_review_comments_path(@review) %>
  <%= link_to "削除", admin_review_path(@review, @shop), method: :delete, data: {confirm: "本当に消しますか？"}, class:"btn btn-danger" %>

  </div>
  </div>