config/routes.rb
Rails.application.routes.draw do
  # 顧客用

devise_for :users, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
 scope module: :public do

 root to: "homes#top"
 get 'search' => 'homes#search', as: 'search'
 get 'top', to: 'homes#top'
 get 'users/mypage' => 'users#mypage', as: 'mypage'
 get 'users/information/edit' => 'users#edit', as: 'edit_information'
 patch 'users/information' => 'users#update', as: 'update_information'
 get 'users/unsubscribe' => 'users#unsubscribe', as: 'confirm_unsubscribe'
 put 'users/information' => 'users#update'
 patch 'users/withdraw' => 'users#withdraw', as: 'withdraw_user'
#  get 'shops/:id/menu' => 'shops#menu', as: 'shop_menu'
 #get 'shops/:id/reviews' => 'reviews#index', as: 'shop_reviews'
 #get 'shops/:id/reviews/new' => 'shops#new_review', as: 'new_review'
 #resources :reviews, only: [:index,:show,:create,:new,:edit,:update,:destroy]
 resources :users, only: [:index,:show,:edit,:update] do
     resources :reviews
     #get 'myreview' => 'users#myreview'
 end
 resources :shops, only: [:index,:new,:create,:show,:edit,:update] do

   resources :reviews
   resources :menus, only: [:index,:new,:create,:destroy]

 end
 
 resources :reviews do
     resources :review_comments, only: [:index, :create, :destroy]
 end

 resources :genres, only: [:index]

 end


# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
namespace :admin do

get 'top' => 'homes#top', as: 'top'
get "about", to: "homes#about"
get 'search' => 'homes#search', as: 'search'
resources :shops do
  resources :reviews, only: [:index,:show,:destroy]
  resources :menus, only: [:index,:new,:create,:edit,:update,:destroy]
end

 resources :reviews, only: [:index,:show,:destroy] do
      resources :review_comments, only: [:index,:show,:destroy]
 end

resources :genres,only: [:index,:create,:edit,:update]

resources :users, only: [:index, :show, :edit, :update] 
  

end
end

app/models/menu.rb
class Menu < ApplicationRecord
  
  belongs_to :shop
  belongs_to :genre
  
  validates :name, presence: true
  validates :price, presence: true
  
  scope :where_genre_active, -> { joins(:genre).where(genres: { is_active: true }) }
  
  
end

app/controllers/admin/menus_controller.rb
class Admin::MenusController < ApplicationController
  before_action :authenticate_admin!
  
  def new
    @menu = Menu.new
  end

  def index
    @shop =  Shop.find(params[:shop_id])
    @menus = @shop.menus.page(params[:page])
    @all_menus_count = @menus.count
  end

  def create
    shop = Shop.find(params[:shop_id])
    genre = Genre.find(menu_params[:genre_id])
    @menu = Menu.new(menu_params)
    @menu.shop_id = shop.id
    @menu.genre_id = genre.id
    @menu.save ? (redirect_to admin_shop_menus_path(shop.id, @menu.id)) : (render :new)
  end

   def show
     @menu = Menu.find(params[:id])
   end


  def destroy
  @shop = Shop.find(params[:shop_id])
  @menu = @shop.menus.find(params[:id])

  if @menu.destroy
    redirect_to admin_shop_menus_path(@shop)
  end
  end

  private

  def menu_params
    params.require(:menu).permit(:genre_id, :shop_id, :name,:price )
  end

end

  

app/helpers/admin/menus_helper.rb
module Admin::MenusHelper
end

app/views/admin/menus/_index.html.erb
<section class="wrapper flex">
	<div class="inner">

			<h2 class="section-ttl">メニュー一覧 (全<%= @all_menus_count %>件)</h2>

	<table class="table">
	<thead>

	</thead>
	<tbody>
	  <th>メニュー名</th>
			<th>価格</th>
			<th>ジャンル</th>
			<th></th>
		<% @menus.each do |menu| %>


			<tr>
				<td><%= menu.name %></td>
				<td><%= menu.price %></td>
				<td><%= menu.genre.name %></td>
				<td><%= link_to "削除", admin_shop_menu_path(@shop,menu.id), method: :delete, "data-confirm" => "#{menu.name}をメニューから削除します。よろしいでしょうか？", class: "btn btn-danger" %></td>

			</tr>


		<% end %>
	</tbody>
</table>
<h4><%= link_to 'メニュー新規登録',new_admin_shop_menu_path %></h4>
<h4><%=link_to '店舗へ戻る',admin_shop_path(@shop) %></h4>


	</div>
</section>

app/views/admin/menus/index.html.erb
<section class="wrapper flex">
	<div class="inner">

		<% if @menus.first %>
			<%= render 'admin/menus/index', menus: @menus %>
			<%= paginate @menus %>
		<% else %>
			<h3>登録されているメニューはありません。</h3>

		<% end %>
	</div>
</section>

app/views/admin/menus/new.html.erb
<%= form_with model:@menu, url: admin_shop_menus_path do |f| %>
	<%= render 'layouts/error_messages', resource: @menu %>
	
	
<div class="flex">
	<div class="container">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h5 class="text-dark bg-light p-4 mb-0">メニュー新規登録</h5>
      <div class="form-body p-4">
<form>
<div><%= f.label :name, "メニュー名" %></div>
<div><%= f.text_field :name %></div>
				
<div><%= f.label :price, "価格" %></div>
<div><%= f.text_field :price %></div>

<div><%= f.label :genre_id, "ジャンル" %></div>
<div><%= f.collection_select :genre_id, Genre.all, :id, :name %></div>

<div class="flex align-center pl5">
	<%= f.submit "投稿", class: "btn btn-primary" %>
</div>

</form>
				</div>
		</div>
	</div>
</div>
</div>
    
<% end %>