config/routes.rb
Rails.application.routes.draw do
  # 顧客用

devise_for :users, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
 scope module: :public do

 root to: "homes#top"
 get 'search' => 'homes#search', as: 'search'
 get 'top', to: 'homes#top'
 get 'users/mypage' => 'users#mypage', as: 'mypage'
 get 'users/information/edit' => 'users#edit', as: 'edit_information'
 patch 'users/information' => 'users#update', as: 'update_information'
 get 'users/unsubscribe' => 'users#unsubscribe', as: 'confirm_unsubscribe'
 put 'users/information' => 'users#update'
 patch 'users/withdraw' => 'users#withdraw', as: 'withdraw_user'
#  get 'shops/:id/menu' => 'shops#menu', as: 'shop_menu'
 #get 'shops/:id/reviews' => 'reviews#index', as: 'shop_reviews'
 #get 'shops/:id/reviews/new' => 'shops#new_review', as: 'new_review'
 #resources :reviews, only: [:index,:show,:create,:new,:edit,:update,:destroy]
 resources :users, only: [:index,:show,:edit,:update] do
     resources :reviews
     #get 'myreview' => 'users#myreview'
 end
 resources :shops, only: [:index,:new,:create,:show,:edit,:update] do

   resources :reviews
   resources :menus, only: [:index,:new,:create,:destroy]

 end
 
 resources :reviews do
     resources :review_comments, only: [:index, :create, :destroy]
 end

 resources :genres, only: [:index]

 end


# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
namespace :admin do

get 'top' => 'homes#top', as: 'top'
get "about", to: "homes#about"
get 'search' => 'homes#search', as: 'search'
resources :shops do
  resources :reviews, only: [:index,:show,:destroy]
  resources :menus, only: [:index,:new,:create,:edit,:update,:destroy]
end

 resources :reviews, only: [:index,:show,:destroy] do
      resources :review_comments, only: [:index,:show,:destroy]
 end

resources :genres,only: [:index,:create,:edit,:update]

resources :users, only: [:index, :show, :edit, :update] 
  

end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many :menus
  
  
end

app/models/menu.rb
class Menu < ApplicationRecord
  
  belongs_to :shop
  belongs_to :genre
  
  validates :name, presence: true
  validates :price, presence: true
  
  scope :where_genre_active, -> { joins(:genre).where(genres: { is_active: true }) }
  
  
end

app/models/review.rb
class Review < ApplicationRecord
  
  has_many :review_comments
  
  
  belongs_to :user
  belongs_to :shop
  
  validates :title, presence: true
  validates :eated_menu, presence: true
  validates :comment, presence: true, length:{maximum:1000}
  validates :star, presence: true
 
end

app/models/review_comment.rb
class ReviewComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :review
  validates :comment, presence: true,length:{maximum:300}
  
end

app/models/shop.rb
class Shop < ApplicationRecord
  
  has_many :reviews
  has_many :menus
  
  validates :shop_name, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
  validates :opening_time, presence: true
  validates :holiday, presence: true
  
   
  
 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_many :reviews, dependent: :destroy
         has_many :review_comments, dependent: :destroy
         
         
  validates :email, presence: true
  validates :nickname, presence: true
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  
  
  def top
  end
  
  def search
    @model = params['search']['model']
    @content = params['search']['content']
    @method = params['search']['method']
    @result = search_for(@model, @content, @method)
  end

  private

  def search_for(model, content, method)
    if model == 'user'
      if method == 'forward'
        User.where(
          'nickname LIKE ? ',
          "#{content}%"
        )
      elsif method == 'backward'
        User.where(
          'nickname LIKE ? ',
          "%#{content}", 
        )
      elsif method == 'perfect'
        User.where(
          'nickname = ?',
          content, 
        )
      else # partial
          User.where(
          'nickname LIKE ? ',
          "%#{content}%", 
        )
      end
    elsif model == 'shop'
      if method == 'forward'
        Shop.where('shop_name LIKE ?', content + '%')
      elsif method == 'backward'
        Shop.where('shop_name LIKE ?', '%' + content)
      elsif method == 'perfect'
        Shop.where(shop_name: content)
      else # partial
        Shop.where('shop_name LIKE ?', '%' + content + '%')
      end
    else
      [] 
    end
  end
end

app/controllers/admin/menus_controller.rb
class Admin::MenusController < ApplicationController
  before_action :authenticate_admin!
  
  def new
    @menu = Menu.new
  end

  def index
    @shop =  Shop.find(params[:shop_id])
    @menus = @shop.menus.page(params[:page])
    @all_menus_count = @menus.count
  end

  def create
    shop = Shop.find(params[:shop_id])
    genre = Genre.find(menu_params[:genre_id])
    @menu = Menu.new(menu_params)
    @menu.shop_id = shop.id
    @menu.genre_id = genre.id
    @menu.save ? (redirect_to admin_shop_menus_path(shop.id, @menu.id)) : (render :new)
  end

   def show
     @menu = Menu.find(params[:id])
   end


  def destroy
  @shop = Shop.find(params[:shop_id])
  @menu = @shop.menus.find(params[:id])

  if @menu.destroy
    redirect_to admin_shop_menus_path(@shop)
  end
  end

  private

  def menu_params
    params.require(:menu).permit(:genre_id, :shop_id, :name,:price )
  end

end

  

app/controllers/admin/shops_controller.rb
class Admin::ShopsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @shop = Shop.new
  end

  def index
    @shops = Shop.all.page(params[:page])
    @all_shops_count = @shops.count
  end

  def create
    @shop = Shop.new(shop_params)
    @shop.save ? (redirect_to admin_shop_path(@shop)) : (render :new)
  end

   def show
     @shop = Shop.find(params[:id])
   end

  def edit
     @shop = Shop.find(params[:id])
  end

  def update
    @shop = Shop.find(params[:id])
    @shop.update(shop_params) ? (redirect_to admin_shop_path(@shop)) : (render :edit)
  end
  
  def destroy
    @shop = Shop.find(params[:id])
    
    if @shop.destroy
    redirect_to admin_shops_path
    end
  end

  private

  def shop_params
    params.require(:shop).permit(:shop_name, :address, :telephone_number, :opening_time, :holiday, )
  end


end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  before_action :ensure_user, only: [:show, :edit, :update]

  def index
    @users = User.page(params[:page])
  end

  def show
    @reviews = @user.reviews.page(params[:page])
  end

  def edit
  end

  def update
    @user.update(user_params) ? (redirect_to admin_user_path(@user)) : (render :edit)
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :is_active)
  end

  def ensure_user
    @user = User.find(params[:id])
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  

end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/menus_helper.rb
module Admin::MenusHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admin/shops_helper.rb
module Admin::ShopsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RamenLog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

 <body>
    <header class="<%= (admin_signed_in? ? "admin_header" : "" ) %>">
      <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="justify-content-end row w-100">
          <h1><%= link_to 'RamenLog', (admin_signed_in? ? admin_top_path : root_path ), class: "col-2" %></h1>
            <div class="collapse navbar-collapse show col-10" id="navbarNavDropdown">
                <ul class="navbar-nav ml-auto">
                  <% if admin_signed_in? %>
                  <li class="ml-2"><%= link_to 'ログアウト', destroy_admin_session_path, method: :delete %></li>

                  <% elsif user_signed_in? %>
                     <p>ようこそ、<%= current_user.nickname %>さん!</p>
                    <li class="ml-2" ><%= link_to 'マイページ', mypage_path %></li>
                    <li class="ml-2" ><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>

                  <% else %>

                    
                    <li class="ml-2"><%= link_to '新規登録', new_user_registration_path %></li>
                    <li class="ml-2"><%= link_to 'ログイン', new_user_session_path %></li>
                  <% end %>
                 </ul>
                 </div>
           <div class="search">
             
            <% if admin_signed_in? %>

           <%= form_tag(admin_search_path, method: :get) do %>
            <%= text_field_tag "search[content]", "", :placeholder =>"キーワード" %>
            <%= select_tag "search[model]", options_for_select({ "会員" => "user", "店舗" => "shop" }) %>
            <%= select_tag "search[method]", options_for_select({ "部分一致" => "partial", "前方一致" => "forward", "後方一致" => "backward", "完全一致" => "perfect" }) %>
            <%= submit_tag '検索', class: "btn btn-primary" %>
          <% end %>
          <% elsif user_signed_in? %>
            <%= form_tag(search_path, method: :get) do %>
            <%= text_field_tag "search[content]", "", :placeholder =>"キーワード" %>
            <%= select_tag "search[model]", options_for_select({ "会員" => "user", "店舗" => "shop" }) %>
            <%= select_tag "search[method]", options_for_select({ "部分一致" => "partial", "前方一致" => "forward", "後方一致" => "backward", "完全一致" => "perfect" }) %>
            <%= submit_tag '検索', class: "btn btn-primary" %>
          <% end %>


          <% else %>
           <%= form_tag(search_path, method: :get) do %>
            <%= text_field_tag "search[content]", "", :placeholder =>"キーワード" %>
            <%= select_tag "search[model]", options_for_select({ "会員" => "user", "店舗" => "shop" }) %>
            <%= select_tag "search[method]", options_for_select({ "部分一致" => "partial", "前方一致" => "forward", "後方一致" => "backward", "完全一致" => "perfect" }) %>
            <%= submit_tag '検索', class: "btn btn-primary" %>
          <% end %>


          <% end %>
           </div>
          </div>
      </nav>
    </header>

    <main>
      <%= yield %>
    </main>


  </body>
</html>